# Basic Options
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators = true
shuffle = true
bitrate = 320

[notification_format]
title =" %title"
body = "%artists"

# Theme Gruvbox
[theme]
background = "default"
primary = "#a89984"
secondary = "#928374"
title = "#8ec07c"
playing = "#689d6a"
playing_bg = "#383838"
playing_selected = "#ebdbb2"
highlight = "#d5c4a1"
highlight_bg = "#484848"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar_progress = "#458588"
statusbar_bg = "#282828"
statusbar = "#98971a"
cmdline = "#d5c4a1"
cmdline_bg = "#383838"
search_match = "#fabd2f"
