# Basic Options
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators = true
shuffle = true
bitrate = 320

[notification_format]
title =" %title"
body = "%artists"

# Theme Nord
[theme]
background = "#3B4252"
primary = "#ECEFF4"
secondary = "#4C566A"
title = "#D8DEE9"
playing = "#D8DEE9"
playing_selected = "#ECEFF4"
playing_bg = "#4C566A"
highlight = "#ECEFF4"
highlight_bg = "#4C566A"
error = "#2E3440"
error_bg = "#D8DEE9"
statusbar = "#D8DEE9"
statusbar_progress = "#D8DEE9"
statusbar_bg = "#4C566A"
cmdline = "#ECEFF4"
cmdline_bg = "#4C566A"
